language: node_js
sudo: false
node_js:
  - 0.12
  - 4
  - 5
# NodeJS v4 requires gcc 4.8
env:
  - NODE_ENV=travis CXX="g++-4.8" CC="gcc-4.8"
matrix:
  allow_failures:
    - node_js: 5
after_success:
  - npm run coverage
# gcc 4.8 requires ubuntu-toolchain-r-test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
    - clang
